import os
os.system("python ./sss.py")
os.system("python ./sss2.py")
os.system("python ./sss3.py")
os.system("python ./sss4.py")
os.system("python ./sss5.py")
os.system("python ./sss6.py")
os.system("python ./sss7.py")
os.system("python ./sss8.py")